### ISSUE TITLE
Using a judgment form defined by “define-relation” in a meta-function requires extra parenthesis

### ISSUE THREAD

**Issue by leafac** [racket/redex#90]
**CURRENT BEHAVIOR**

```racket
#lang racket
(require redex)

(define-language L
  [s ::= (b ...)]
  [b ::= 0 1])

(define-relation L
  zero? ⊆ s
  [(zero? (0 ...))])

(define-metafunction L
  convoluted-example : s -> string
  [(convoluted-example s) "was zero" (judgment-holds (zero? s))]
  [(convoluted-example s) "wasn’t zero"])

(term (convoluted-example (0 0)))
```

Errors:

```
zero?: judgment input values do not match its contract;
 (unknown output values indicated by _)
  contract: (zero? (s))
  values: (zero? (0 0))
```

In particular, the issue is the `(judgment-holds (zero? s))` in `convoluted-example`.

**EXPECTED BEHAVIOR**

The code above should execute and output `"was zero"`, the same way the snippet below does:

```racket
#lang racket
(require redex)

(define-language L
  [s ::= (b ...)]
  [b ::= 0 1])

(define-judgment-form L
  #:mode (zero? I)
  #:contract (zero? s)
  [(zero? (0 ...))])

(define-metafunction L
  convoluted-example : s -> string
  [(convoluted-example s) "was zero" (judgment-holds (zero? s))]
  [(convoluted-example s) "wasn’t zero"])

(term (convoluted-example (0 0)))
```

Apart from using `define-judgment-form` instead of `define-relation`, the two programs are the same.

**WORKAROUND**

Add an extra pair of parenthesis around the judgment form’s arguments:

```racket
#lang racket
(require redex)

(define-language L
  [s ::= (b ...)]
  [b ::= 0 1])

(define-relation L
  zero? ⊆ s
  [(zero? (0 ...))])

(define-metafunction L
  convoluted-example : s -> string
  [(convoluted-example s) "was zero" (judgment-holds (zero? (s)))]
  [(convoluted-example s) "wasn’t zero"])

(term (convoluted-example (0 0)))
```

-----

Do you agree this is a problem? Can I help fix it?

Thank you.

**Comment by rfindler** [comment]
I think the actual bug is that `judgment-holds` is not supposed to accept things defined by `define-relation`. Instead when you use `define-relation` you are supposed to be getting something that acts like a metafunction that returns a boolean.  (Try the `judgment-holds` at the top-level.)

This is clearly something that it would be good to improve; Redex knows that `zero?` is defined via `define-relation`, perhaps `judgment-holds` should notice that it has a relation and, instead of rejecting it, accommodate it properly, as you suggest (but the top-level bit has to change too).

Anyway, you currently have to write something like this:

```
#lang racket
(require redex)

(define-language L
  [s ::= (b ...)]
  [b ::= 0 1])

(define-relation L
  zero? ⊆ s
  [(zero? (0 ...))])

(define-metafunction L
  convoluted-example : s -> string
  [(convoluted-example s) "was zero" (where #t (zero? s))]
  [(convoluted-example s) "wasn’t zero"])

(term (convoluted-example (0 0)))
```

**Comment by leafac** [comment]
Thank you for the feedback. If I understand you correctly, this is the code that we’d like to work:

```racket
#lang racket
(require redex)

(define-language L
  [s ::= (b ...)]
  [b ::= 0 1])

(define-relation L
  zero? ⊆ s
  [(zero? (0 ...))])

(define-metafunction L
  convoluted-example : s -> string
  [(convoluted-example s) "was zero" (zero? s)]
  [(convoluted-example s) "wasn’t zero"])

(term (convoluted-example (0 0)))
```

But, currently, it errors:

```
define-metafunction: expected a side-condition, where, or clause-name in: (zero? s)
```

Additionally, regarding relations defined with `define-relation` in `judgment-holds`, we want to do one of the two:

1. Remove the broken support in `define-metafunction`.
2. Fix the broken support in `define-metafunction` and add support to the `judgment-holds` form at the top-level (currently it correctly errors with `judgment-holds: relations not allowed`).

I vote for the first option: it is simpler (a relation defined by `define-relation` is bound to return a boolean, anyway) and more consistent (less redundant ways of achieving the same result).

**Comment by bennn** [comment]
This is the code that should work. And it does work!

```
#lang racket
(require redex)

(define-language L
  [s ::= (b ...)]
  [b ::= 0 1])

(define-relation L
  zero? ⊆ s
  [(zero? (0 ...))])

(define-metafunction L
  convoluted-example : s -> string
  [(convoluted-example s) "was zero" (where #true (zero? s))]
  [(convoluted-example s) "wasn’t zero"])

(term (convoluted-example (0 0)))
```

The error `expected a side condition, ....` is expected, because `(zero? s)` doesn't match the grammar for [`metafunction-extras`](http://docs.racket-lang.org/redex/The_Redex_Reference.html#%28form._%28%28lib._redex%2Freduction-semantics..rkt%29._define-metafunction%29%29)

**Comment by rfindler** [comment]
I think it would make sense to extend "metafunction-extras" to support the case "(<id> <term> ...)" where <id> is bound to a relation. Or, for that matter, a judgment-form. And then the `judgment-holds` in the side-condition would be redundant.

Does that seem right to people?

**Comment by bennn** [comment]
Yes I guess that makes sense, but personally I would avoid that `metafunction-extra`.

(I like using explicit annotations to say "I expect `<id>` is a judgment form" or "I expect `<id>` is a metafunction" --- as opposed to "I expect to pattern-match against a list".)

**Comment by rfindler** [comment]
Oh, that's a good point. Yeah, the right thing to do here is just adjust `judgment-holds` so that it accepts thing defined by `define-relation`.

**Comment by leafac** [comment]
@bennn:

> I like using explicit annotations to say "I expect <id> is a judgment form" or "I expect <id> is a metafunction" --- as opposed to "I expect to pattern-match against a list".

What do you mean by “pattern-match against a list”? I understand the rest of your argument, and it does make sense, but I do not get this part.

-----

I’m confused as to what we decided to do. @rfindler seems to agree with @bennn, who proposed `(where #true (zero? s))`, but then said that we need to adjust `judgment-holds`, leading me to believe that he’s in favor of `(judgment-holds (zero? s))`.

**Comment by rfindler** [comment]
I'm saying that Ben's sentiment about having an explicit construct is a good one, and the way to do that in this case is to go back to what you (@leafac) suggested in the beginning, namely making `judgment-holds` work for relations.

**Comment by bennn** [comment]
@leafac you're right, there's no way to mistake `(zero? s)` in `"was zero" (zero? s)` for a pattern-match. It's not matching against anything.

Still if you gave me the choice between 1. `"was zero" (zero? s)` and 2. `"was zero" (judgment-holds (zero? s))` I would rather write `judgment-holds`

**Comment by leafac** [comment]
Thank you for the clarifications. Here’s the to-do list, as I understand it:

- [ ] Fix `judgment-holds` in `define-metafunction` such that it accepts judgment forms defined with `define-relation` without the extra pair of parenthesis.
- [ ] For consistency, add support for judgment forms defined with `define-relation` in the top-level `judgment-holds` form.
- [ ] Adapt the documentation accordingly.

**Comment by rfindler** [comment]
That sounds right to me!

**Comment by rfindler** [comment]
This turned out to be more complicated than I expected, but I should be able to fix it.

**Comment by leafac** [comment]
@rfindler: Thank you :) If there’s something I can do to help, just let me know.

**Comment by leafac** [comment]
Thanks a lot, @rfindler 😄

**Comment by rfindler** [comment]
This commit came in just after the release branches were created, which means that, by default, it will not be in the release. I'm okay with that, but I wanted to check with others here. Is there a reason to push this into the release?

**Comment by mfelleisen** [comment]
@rfindler summer school?

**Comment by rfindler** [comment]
Yeah, that's a good point. I've pushed them. I'm not sure they are bug free (it got a little bit complicated) but hopefully they are.

**Comment by leafac** [comment]
Will there be a 2017 Redex summer school? Where do I get more information? (The website [mentions the 2015 edition](http://redex.racket-lang.org/summer-school.html).)

**Comment by rfindler** [comment]
There is!

http://summer-school.racket-lang.org/2017/

**Comment by leafac** [comment]
This sounds like fun 😄
